# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: akshare.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'akshare.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rakshare.proto\x12\x07\x61kshare\"z\n\x0b\x43\x61llRequest\x12\n\n\x02\x66n\x18\x01 \x01(\t\x12\x30\n\x06kwargs\x18\x02 \x03(\x0b\x32 .akshare.CallRequest.KwargsEntry\x1a-\n\x0bKwargsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x0c\x43\x61llResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x11\n\tdata_json\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"%\n\x14\x42\x61tchEstimateRequest\x12\r\n\x05\x63odes\x18\x01 \x03(\t\"\x84\x01\n\x0c\x46undEstimate\x12\x11\n\tfund_code\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x65stimate\x18\x03 \x01(\x01\x12\x18\n\x10\x65stimate_percent\x18\x04 \x01(\x01\x12\x10\n\x08last_nav\x18\x05 \x01(\x01\x12\x15\n\restimate_time\x18\x06 \x01(\t\"A\n\x15\x42\x61tchEstimateResponse\x12(\n\testimates\x18\x01 \x03(\x0b\x32\x15.akshare.FundEstimate\"6\n\tNavRecord\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0b\n\x03nav\x18\x02 \x01(\x01\x12\x0e\n\x06\x63hange\x18\x03 \x01(\x01\"\x1e\n\x0eHistoryRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"6\n\x0fHistoryResponse\x12#\n\x07records\x18\x01 \x03(\x0b\x32\x12.akshare.NavRecord2\xdb\x01\n\x07\x41kshare\x12\x33\n\x04\x43\x61ll\x12\x14.akshare.CallRequest\x1a\x15.akshare.CallResponse\x12V\n\x15\x42\x61tchGetFundEstimates\x12\x1d.akshare.BatchEstimateRequest\x1a\x1e.akshare.BatchEstimateResponse\x12\x43\n\x0eGetFundHistory\x12\x17.akshare.HistoryRequest\x1a\x18.akshare.HistoryResponseB&Z$huahua-service/akshare_proto/akshareb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'akshare_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z$huahua-service/akshare_proto/akshare'
  _globals['_CALLREQUEST_KWARGSENTRY']._loaded_options = None
  _globals['_CALLREQUEST_KWARGSENTRY']._serialized_options = b'8\001'
  _globals['_CALLREQUEST']._serialized_start=26
  _globals['_CALLREQUEST']._serialized_end=148
  _globals['_CALLREQUEST_KWARGSENTRY']._serialized_start=103
  _globals['_CALLREQUEST_KWARGSENTRY']._serialized_end=148
  _globals['_CALLRESPONSE']._serialized_start=150
  _globals['_CALLRESPONSE']._serialized_end=210
  _globals['_BATCHESTIMATEREQUEST']._serialized_start=212
  _globals['_BATCHESTIMATEREQUEST']._serialized_end=249
  _globals['_FUNDESTIMATE']._serialized_start=252
  _globals['_FUNDESTIMATE']._serialized_end=384
  _globals['_BATCHESTIMATERESPONSE']._serialized_start=386
  _globals['_BATCHESTIMATERESPONSE']._serialized_end=451
  _globals['_NAVRECORD']._serialized_start=453
  _globals['_NAVRECORD']._serialized_end=507
  _globals['_HISTORYREQUEST']._serialized_start=509
  _globals['_HISTORYREQUEST']._serialized_end=539
  _globals['_HISTORYRESPONSE']._serialized_start=541
  _globals['_HISTORYRESPONSE']._serialized_end=595
  _globals['_AKSHARE']._serialized_start=598
  _globals['_AKSHARE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
