# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import akshare_pb2 as akshare__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in akshare_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AkshareStub:
    """Akshare 数据服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/akshare.Akshare/Call',
                request_serializer=akshare__pb2.CallRequest.SerializeToString,
                response_deserializer=akshare__pb2.CallResponse.FromString,
                _registered_method=True)
        self.BatchGetFundEstimates = channel.unary_unary(
                '/akshare.Akshare/BatchGetFundEstimates',
                request_serializer=akshare__pb2.BatchEstimateRequest.SerializeToString,
                response_deserializer=akshare__pb2.BatchEstimateResponse.FromString,
                _registered_method=True)
        self.GetFundHistory = channel.unary_unary(
                '/akshare.Akshare/GetFundHistory',
                request_serializer=akshare__pb2.HistoryRequest.SerializeToString,
                response_deserializer=akshare__pb2.HistoryResponse.FromString,
                _registered_method=True)


class AkshareServicer:
    """Akshare 数据服务
    """

    def Call(self, request, context):
        """通用调用：可调用任意 akshare 函数，结果以 JSON 字符串返回
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetFundEstimates(self, request, context):
        """高频接口：基金实时估值（批量）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFundHistory(self, request, context):
        """高频接口：基金历史净值
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AkshareServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=akshare__pb2.CallRequest.FromString,
                    response_serializer=akshare__pb2.CallResponse.SerializeToString,
            ),
            'BatchGetFundEstimates': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetFundEstimates,
                    request_deserializer=akshare__pb2.BatchEstimateRequest.FromString,
                    response_serializer=akshare__pb2.BatchEstimateResponse.SerializeToString,
            ),
            'GetFundHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFundHistory,
                    request_deserializer=akshare__pb2.HistoryRequest.FromString,
                    response_serializer=akshare__pb2.HistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'akshare.Akshare', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('akshare.Akshare', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Akshare:
    """Akshare 数据服务
    """

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akshare.Akshare/Call',
            akshare__pb2.CallRequest.SerializeToString,
            akshare__pb2.CallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetFundEstimates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akshare.Akshare/BatchGetFundEstimates',
            akshare__pb2.BatchEstimateRequest.SerializeToString,
            akshare__pb2.BatchEstimateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFundHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/akshare.Akshare/GetFundHistory',
            akshare__pb2.HistoryRequest.SerializeToString,
            akshare__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
