// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: akshare_proto/akshare.proto

package akshare

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Akshare_Call_FullMethodName                  = "/akshare.Akshare/Call"
	Akshare_BatchGetFundEstimates_FullMethodName = "/akshare.Akshare/BatchGetFundEstimates"
	Akshare_GetFundHistory_FullMethodName        = "/akshare.Akshare/GetFundHistory"
)

// AkshareClient is the client API for Akshare service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Akshare 数据服务
type AkshareClient interface {
	// 通用调用：可调用任意 akshare 函数，结果以 JSON 字符串返回
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// 高频接口：基金实时估值（批量）
	BatchGetFundEstimates(ctx context.Context, in *BatchEstimateRequest, opts ...grpc.CallOption) (*BatchEstimateResponse, error)
	// 高频接口：基金历史净值
	GetFundHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error)
}

type akshareClient struct {
	cc grpc.ClientConnInterface
}

func NewAkshareClient(cc grpc.ClientConnInterface) AkshareClient {
	return &akshareClient{cc}
}

func (c *akshareClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, Akshare_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akshareClient) BatchGetFundEstimates(ctx context.Context, in *BatchEstimateRequest, opts ...grpc.CallOption) (*BatchEstimateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEstimateResponse)
	err := c.cc.Invoke(ctx, Akshare_BatchGetFundEstimates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *akshareClient) GetFundHistory(ctx context.Context, in *HistoryRequest, opts ...grpc.CallOption) (*HistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryResponse)
	err := c.cc.Invoke(ctx, Akshare_GetFundHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AkshareServer is the server API for Akshare service.
// All implementations must embed UnimplementedAkshareServer
// for forward compatibility.
//
// Akshare 数据服务
type AkshareServer interface {
	// 通用调用：可调用任意 akshare 函数，结果以 JSON 字符串返回
	Call(context.Context, *CallRequest) (*CallResponse, error)
	// 高频接口：基金实时估值（批量）
	BatchGetFundEstimates(context.Context, *BatchEstimateRequest) (*BatchEstimateResponse, error)
	// 高频接口：基金历史净值
	GetFundHistory(context.Context, *HistoryRequest) (*HistoryResponse, error)
	mustEmbedUnimplementedAkshareServer()
}

// UnimplementedAkshareServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAkshareServer struct{}

func (UnimplementedAkshareServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedAkshareServer) BatchGetFundEstimates(context.Context, *BatchEstimateRequest) (*BatchEstimateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetFundEstimates not implemented")
}
func (UnimplementedAkshareServer) GetFundHistory(context.Context, *HistoryRequest) (*HistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundHistory not implemented")
}
func (UnimplementedAkshareServer) mustEmbedUnimplementedAkshareServer() {}
func (UnimplementedAkshareServer) testEmbeddedByValue()                 {}

// UnsafeAkshareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AkshareServer will
// result in compilation errors.
type UnsafeAkshareServer interface {
	mustEmbedUnimplementedAkshareServer()
}

func RegisterAkshareServer(s grpc.ServiceRegistrar, srv AkshareServer) {
	// If the following call panics, it indicates UnimplementedAkshareServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Akshare_ServiceDesc, srv)
}

func _Akshare_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkshareServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Akshare_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkshareServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Akshare_BatchGetFundEstimates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkshareServer).BatchGetFundEstimates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Akshare_BatchGetFundEstimates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkshareServer).BatchGetFundEstimates(ctx, req.(*BatchEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Akshare_GetFundHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AkshareServer).GetFundHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Akshare_GetFundHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AkshareServer).GetFundHistory(ctx, req.(*HistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Akshare_ServiceDesc is the grpc.ServiceDesc for Akshare service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Akshare_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akshare.Akshare",
	HandlerType: (*AkshareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Akshare_Call_Handler,
		},
		{
			MethodName: "BatchGetFundEstimates",
			Handler:    _Akshare_BatchGetFundEstimates_Handler,
		},
		{
			MethodName: "GetFundHistory",
			Handler:    _Akshare_GetFundHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "akshare_proto/akshare.proto",
}
