// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: akshare_proto/akshare.proto

package akshare

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用调用请求：akshare 函数名 + 关键字参数
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`                                                                                   // akshare 函数名，如 "fund_estimate"
	Kwargs        map[string]string      `protobuf:"bytes,2,rep,name=kwargs,proto3" json:"kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 关键字参数，如 {"code":"000001"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *CallRequest) GetKwargs() map[string]string {
	if x != nil {
		return x.Kwargs
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	DataJson      string                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"` // 结果序列化为 JSON 字符串
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CallResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchEstimateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEstimateRequest) Reset() {
	*x = BatchEstimateRequest{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEstimateRequest) ProtoMessage() {}

func (x *BatchEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEstimateRequest.ProtoReflect.Descriptor instead.
func (*BatchEstimateRequest) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{2}
}

func (x *BatchEstimateRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type FundEstimate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FundCode        string                 `protobuf:"bytes,1,opt,name=fund_code,json=fundCode,proto3" json:"fund_code,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Estimate        float64                `protobuf:"fixed64,3,opt,name=estimate,proto3" json:"estimate,omitempty"`
	EstimatePercent float64                `protobuf:"fixed64,4,opt,name=estimate_percent,json=estimatePercent,proto3" json:"estimate_percent,omitempty"`
	LastNav         float64                `protobuf:"fixed64,5,opt,name=last_nav,json=lastNav,proto3" json:"last_nav,omitempty"`
	EstimateTime    string                 `protobuf:"bytes,6,opt,name=estimate_time,json=estimateTime,proto3" json:"estimate_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FundEstimate) Reset() {
	*x = FundEstimate{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundEstimate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundEstimate) ProtoMessage() {}

func (x *FundEstimate) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundEstimate.ProtoReflect.Descriptor instead.
func (*FundEstimate) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{3}
}

func (x *FundEstimate) GetFundCode() string {
	if x != nil {
		return x.FundCode
	}
	return ""
}

func (x *FundEstimate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FundEstimate) GetEstimate() float64 {
	if x != nil {
		return x.Estimate
	}
	return 0
}

func (x *FundEstimate) GetEstimatePercent() float64 {
	if x != nil {
		return x.EstimatePercent
	}
	return 0
}

func (x *FundEstimate) GetLastNav() float64 {
	if x != nil {
		return x.LastNav
	}
	return 0
}

func (x *FundEstimate) GetEstimateTime() string {
	if x != nil {
		return x.EstimateTime
	}
	return ""
}

type BatchEstimateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estimates     []*FundEstimate        `protobuf:"bytes,1,rep,name=estimates,proto3" json:"estimates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEstimateResponse) Reset() {
	*x = BatchEstimateResponse{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEstimateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEstimateResponse) ProtoMessage() {}

func (x *BatchEstimateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEstimateResponse.ProtoReflect.Descriptor instead.
func (*BatchEstimateResponse) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{4}
}

func (x *BatchEstimateResponse) GetEstimates() []*FundEstimate {
	if x != nil {
		return x.Estimates
	}
	return nil
}

type NavRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Nav           float64                `protobuf:"fixed64,2,opt,name=nav,proto3" json:"nav,omitempty"`
	Change        float64                `protobuf:"fixed64,3,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavRecord) Reset() {
	*x = NavRecord{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavRecord) ProtoMessage() {}

func (x *NavRecord) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavRecord.ProtoReflect.Descriptor instead.
func (*NavRecord) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{5}
}

func (x *NavRecord) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *NavRecord) GetNav() float64 {
	if x != nil {
		return x.Nav
	}
	return 0
}

func (x *NavRecord) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*NavRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_akshare_proto_akshare_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_akshare_proto_akshare_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_akshare_proto_akshare_proto_rawDescGZIP(), []int{7}
}

func (x *HistoryResponse) GetRecords() []*NavRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_akshare_proto_akshare_proto protoreflect.FileDescriptor

const file_akshare_proto_akshare_proto_rawDesc = "" +
	"\n" +
	"\x1bakshare_proto/akshare.proto\x12\aakshare\"\x92\x01\n" +
	"\vCallRequest\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x128\n" +
	"\x06kwargs\x18\x02 \x03(\v2 .akshare.CallRequest.KwargsEntryR\x06kwargs\x1a9\n" +
	"\vKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\fCallResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\tR\bdataJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x14BatchEstimateRequest\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\"\xc6\x01\n" +
	"\fFundEstimate\x12\x1b\n" +
	"\tfund_code\x18\x01 \x01(\tR\bfundCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bestimate\x18\x03 \x01(\x01R\bestimate\x12)\n" +
	"\x10estimate_percent\x18\x04 \x01(\x01R\x0festimatePercent\x12\x19\n" +
	"\blast_nav\x18\x05 \x01(\x01R\alastNav\x12#\n" +
	"\restimate_time\x18\x06 \x01(\tR\festimateTime\"L\n" +
	"\x15BatchEstimateResponse\x123\n" +
	"\testimates\x18\x01 \x03(\v2\x15.akshare.FundEstimateR\testimates\"I\n" +
	"\tNavRecord\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x10\n" +
	"\x03nav\x18\x02 \x01(\x01R\x03nav\x12\x16\n" +
	"\x06change\x18\x03 \x01(\x01R\x06change\"$\n" +
	"\x0eHistoryRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"?\n" +
	"\x0fHistoryResponse\x12,\n" +
	"\arecords\x18\x01 \x03(\v2\x12.akshare.NavRecordR\arecords2\xdb\x01\n" +
	"\aAkshare\x123\n" +
	"\x04Call\x12\x14.akshare.CallRequest\x1a\x15.akshare.CallResponse\x12V\n" +
	"\x15BatchGetFundEstimates\x12\x1d.akshare.BatchEstimateRequest\x1a\x1e.akshare.BatchEstimateResponse\x12C\n" +
	"\x0eGetFundHistory\x12\x17.akshare.HistoryRequest\x1a\x18.akshare.HistoryResponseB&Z$huahua-service/akshare_proto/akshareb\x06proto3"

var (
	file_akshare_proto_akshare_proto_rawDescOnce sync.Once
	file_akshare_proto_akshare_proto_rawDescData []byte
)

func file_akshare_proto_akshare_proto_rawDescGZIP() []byte {
	file_akshare_proto_akshare_proto_rawDescOnce.Do(func() {
		file_akshare_proto_akshare_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_akshare_proto_akshare_proto_rawDesc), len(file_akshare_proto_akshare_proto_rawDesc)))
	})
	return file_akshare_proto_akshare_proto_rawDescData
}

var file_akshare_proto_akshare_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_akshare_proto_akshare_proto_goTypes = []any{
	(*CallRequest)(nil),           // 0: akshare.CallRequest
	(*CallResponse)(nil),          // 1: akshare.CallResponse
	(*BatchEstimateRequest)(nil),  // 2: akshare.BatchEstimateRequest
	(*FundEstimate)(nil),          // 3: akshare.FundEstimate
	(*BatchEstimateResponse)(nil), // 4: akshare.BatchEstimateResponse
	(*NavRecord)(nil),             // 5: akshare.NavRecord
	(*HistoryRequest)(nil),        // 6: akshare.HistoryRequest
	(*HistoryResponse)(nil),       // 7: akshare.HistoryResponse
	nil,                           // 8: akshare.CallRequest.KwargsEntry
}
var file_akshare_proto_akshare_proto_depIdxs = []int32{
	8, // 0: akshare.CallRequest.kwargs:type_name -> akshare.CallRequest.KwargsEntry
	3, // 1: akshare.BatchEstimateResponse.estimates:type_name -> akshare.FundEstimate
	5, // 2: akshare.HistoryResponse.records:type_name -> akshare.NavRecord
	0, // 3: akshare.Akshare.Call:input_type -> akshare.CallRequest
	2, // 4: akshare.Akshare.BatchGetFundEstimates:input_type -> akshare.BatchEstimateRequest
	6, // 5: akshare.Akshare.GetFundHistory:input_type -> akshare.HistoryRequest
	1, // 6: akshare.Akshare.Call:output_type -> akshare.CallResponse
	4, // 7: akshare.Akshare.BatchGetFundEstimates:output_type -> akshare.BatchEstimateResponse
	7, // 8: akshare.Akshare.GetFundHistory:output_type -> akshare.HistoryResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_akshare_proto_akshare_proto_init() }
func file_akshare_proto_akshare_proto_init() {
	if File_akshare_proto_akshare_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_akshare_proto_akshare_proto_rawDesc), len(file_akshare_proto_akshare_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_akshare_proto_akshare_proto_goTypes,
		DependencyIndexes: file_akshare_proto_akshare_proto_depIdxs,
		MessageInfos:      file_akshare_proto_akshare_proto_msgTypes,
	}.Build()
	File_akshare_proto_akshare_proto = out.File
	file_akshare_proto_akshare_proto_goTypes = nil
	file_akshare_proto_akshare_proto_depIdxs = nil
}
